---
deployment:
  tasks:
    # Deploy To Mechanic Shops
    - export HARMONY=/home/cloudthe/harmonycrm.fluxhosts.com
    - export SOL=/home/cloudthe/sol.legacyrp.company
    - export PBAY=/home/cloudthe/pbay.legacyrp.company
    - export MIRRORPARK=/home/cloudthe/mpar.legacyrp.company
    - export MOSLEYS=/home/cloudthe/mosleys.legacyrp.company
    - export HAYES=/home/cloudthe/hayes.legacyrp.company
    # Deploy To Bars/Clubs/ Etc madrazos
    - export MADRAZOS=/home/cloudthe/madrazos.legacyrp.company
    - export BAHAMA=/home/cloudthe/bahama-mamas.legacyrp.company
    - export TLL=/home/cloudthe/tequilala.legacyrp.company
    - export ARCADE=/home/cloudthe/videogeddon.legacyrp.company
    - export SPLITSIDES=/home/cloudthe/splitsides.legacyrp.company
    - export YELLOWJACK=/home/cloudthe/yellowjack.legacyrp.company
    # Other
    - export DOJ=/home/cloudthe/doj.legacyrp.company
    - export DEV=/home/cloudthe/dev.legacyrp.company
    # Start Deployment
    - command: php artisan down --status=418 --retry=60
      base_directory: $DEV
    - command: php artisan down --status=418 --retry=60
      base_directory: $HARMONY
    - command: php artisan down --status=418 --retry=60
      base_directory: $SOL
    - command: php artisan down --status=418 --retry=60
      base_directory: $PBAY
    - command: php artisan down --status=418 --retry=60
      base_directory: $MIRRORPARK
    - command: php artisan down --status=418 --retry=60
      base_directory: $MOSLEYS
    - command: php artisan down --status=418 --retry=60
      base_directory: $HAYES
    - command: php artisan down --status=418 --retry=60
      base_directory: $MADRAZOS
    - command: php artisan down --status=418 --retry=60
      base_directory: $BAHAMA
    - command: php artisan down --status=418 --retry=60
      base_directory: $TLL
    - command: php artisan down --status=418 --retry=60
      base_directory: $ARCADE
    - command: php artisan down --status=418 --retry=60
      base_directory: $SPLITSIDES
    - command: php artisan down --status=418 --retry=60
      base_directory: $YELLOWJACK
    - command: php artisan down --status=418 --retry=60
      base_directory: $DOJ
    - /bin/cp -R * $DEV
    - /bin/cp -R * $HARMONY
    - /bin/cp -R * $SOL
    - /bin/cp -R * $PBAY
    - /bin/cp -R * $MIRRORPARK
    - /bin/cp -R * $MOSLEYS
    - /bin/cp -R * $HAYES
    - /bin/cp -R * $MADRAZOS
    - /bin/cp -R * $BAHAMA
    - /bin/cp -R * $TLL
    - /bin/cp -R * $ARCADE
    - /bin/cp -R * $SPLITSIDES
    - /bin/cp -R * $YELLOWJACK
    - /bin/cp -R * $DOJ
    - command: php artisan up
      base_directory: $DEV
    - command: php artisan up
      base_directory: $HARMONY
    - command: php artisan up
      base_directory: $SOL
    - command: php artisan up
      base_directory: $PBAY
    - command: php artisan up
      base_directory: $MIRRORPARK
    - command: php artisan up
      base_directory: $MOSLEYS
    - command: php artisan up
      base_directory: $HAYES
    - command: php artisan up
      base_directory: $MADRAZOS
    - command: php artisan down up
      base_directory: $BAHAMA
    - command: php artisan up
      base_directory: $TLL
    - command: php artisan up
      base_directory: $ARCADE
    - command: php artisan up
      base_directory: $SPLITSIDES
    - command: php artisan up
      base_directory: $YELLOWJACK
    - command: php artisan up
      base_directory: $DOJ
